spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:sqlite:./db.sqlite3
    driverClassName: org.sqlite.JDBC
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.community.dialect.SQLiteDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    url: jdbc:sqlite:./db.sqlite3
    validate-on-migrate: true
  profiles:
    include: env
app:
  action-data-clean-min: 60
  invite-link: "https://discord.gg/EyfCfV7zaS"
